In [2]:
# After preprocessing
# Word Embedding (BOW / TF-IDF)
# We will also train the model (Machine Learning Algorithm for SPAM/HAM Detection)
# Assignments

In [3]:
import pandas as pd
messages=pd.read_csv("../Dataset/SMSSpamCollection.txt",sep="\t",names=["label","message"])

In [4]:
messages

     label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [5]:
# Data Cleaning and Preprocessing
import re
import nltk
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\agarw\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [6]:
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
ps=PorterStemmer()

In [7]:
corpus=[]
for i in range(0,len(messages)):
    review=re.sub("[^a-zA-z]"," ",messages["message"][i])
    review=review.lower()
    words=review.split()
    words=[ps.stem(word) for word in words if word not in set(stopwords.words("english"))]
    review=" ".join(words)
    corpus.append(review)

In [8]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl week word back like fun still tb ok xxx std chg send rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash pound txt csh send cost p day day tsandc appli repli hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'search right word thank breather promis wont take help grant fulfil promis wonder bless time',
 'date sunday',
 'xxxmobilemovieclub use credit click wap link next txt messag click http wap xxxmobilemovieclub com n qjkgighjjgcbl',
 'oh k watch',
 'eh u rememb spell name ye v naughti make v wet',
 'fine way u feel way gota b',
 'england v macedonia dont miss goal team news txt ur nation team eg england tri wale scotland txt poboxox w wq',
 'serious spell name',
 'go tri month ha ha joke',
 'pay first lar da stock comin',
 'aft finish lunch go str lor ard smth lor u finish ur lunch alreadi',
 'ffffffffff alright way meet sooner',
 'forc eat slice realli hungri tho suck mark get worri know sick turn pizza lol',
 'lol alway convinc',
 'catch bu fri egg make tea eat mom left dinner feel love',
 'back amp pack car let know room',
 'ahhh work vagu rememb feel like lol',
 'wait still clear sure sarcast x want live us',
 'yeah got v apologet n fallen actin like spoilt child got caught till go badli cheer',
 'k tell anyth',
 'fear faint housework quick cuppa',
 'thank subscript rington uk mobil charg month pleas confirm repli ye repli charg',
 'yup ok go home look time msg xuhui go learn nd may lesson',
 'oop let know roommat done',
 'see letter b car',
 'anyth lor u decid',
 'hello saturday go text see decid anyth tomo tri invit anyth',
 'pl go ahead watt want sure great weekend abiola',
 'forget tell want need crave love sweet arabian steed mmmmmm yummi',
 'rodger burn msg tri call repli sm free nokia mobil free camcord pleas call deliveri tomorrow',
 'see',
 'great hope like man well endow lt gt inch',
 'call messag miss call',
 'get hep b immunis nigeria',
 'fair enough anyth go',
 'yeah hope tyler could mayb ask around bit',
 'u know stubborn even want go hospit kept tell mark weak sucker hospit weak sucker',
 'think first time saw class',
 'gram usual run like lt gt half eighth smarter though get almost whole second gram lt gt',
 'k fyi x ride earli tomorrow morn crash place tonight',
 'wow never realiz embarass accomod thought like sinc best could alway seem happi cave sorri give sorri offer sorri room embarass',
 'sm ac sptv new jersey devil detroit red wing play ice hockey correct incorrect end repli end sptv',
 'know mallika sherawat yesterday find lt url gt',
 'congrat year special cinema pass call c suprman v matrix starwar etc free bx ip pm dont miss',
 'sorri call later meet',
 'tell reach',
 'ye gauti sehwag odi seri',
 'gonna pick burger way home even move pain kill',
 'ha ha ha good joke girl situat seeker',
 'part check iq',
 'sorri roommat took forev ok come',
 'ok lar doubl check wif da hair dresser alreadi said wun cut v short said cut look nice',
 'valu custom pleas advis follow recent review mob award bonu prize call',
 'today song dedic day song u dedic send ur valuabl frnd first rpli',
 'urgent ur award complimentari trip eurodisinc trav aco entri claim txt di morefrmmob shracomorsglsuplt ls aj',
 'hear new divorc barbi come ken stuff',
 'plane give month end',
 'wah lucki man save money hee',
 'finish class',
 'hi babe im home wanna someth xx',
 'k k perform',
 'u call',
 'wait machan call free',
 'that cool gentleman treat digniti respect',
 'like peopl much shi pa',
 'oper lt gt',
 'still look job much ta earn',
 'sorri call later',
 'k call ah',
 'ok way home hi hi',
 'place man',
 'yup next stop',
 'call later network urgnt sm',
 'real u get yo need ticket one jacket done alreadi use multi',
 'ye start send request make pain came back back bed doubl coin factori gotta cash nitro',
 'realli still tonight babe',
 'ela kano il download come wen ur free',
 'yeah stand close tho catch someth',
 'sorri pain ok meet anoth night spent late afternoon casualti mean done stuff moro includ time sheet sorri',
 'smile pleasur smile pain smile troubl pour like rain smile sum hurt u smile becoz someon still love see u smile',
 'pleas call custom servic repres pm guarante cash prize',
 'havent plan buy later check alreadi lido got show e afternoon u finish work alreadi',
 'free rington wait collect simpli text password mix verifi get usher britney fml po box mk h ppw',
 'watch telugu movi wat abt u',
 'see finish load loan pay',
 'hi wk ok hol ye bit run forgot hairdress appoint four need get home n shower beforehand caus prob u',
 'see cup coffe anim',
 'pleas text anymor noth els say',
 'okay name ur price long legal wen pick u ave x am xx',
 'still look car buy gone drive test yet',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'wow right mean guess gave boston men chang search locat nyc someth chang cuz signin page still say boston',
 'umma life vava umma love lot dear',
 'thank lot wish birthday thank make birthday truli memor',
 'aight hit get cash',
 'would ip address test consid comput minecraft server',
 'know grumpi old peopl mom like better lie alway one play joke',
 'dont worri guess busi',
 'plural noun research',
 'go dinner msg',
 'ok wif co like tri new thing scare u dun like mah co u said loud',
 'gent tri contact last weekend draw show prize guarante call claim code k valid hr ppm',
 'wa ur openin sentenc formal anyway fine juz tt eatin much n puttin weight haha anythin special happen',
 'enter cabin pa said happi b day boss felt special askd lunch lunch invit apart went',
 'winner u special select receiv holiday flight inc speak live oper claim p min',
 'goodo ye must speak friday egg potato ratio tortilla need',
 'hmm uncl inform pay school directli pl buy food',
 'privat account statement show unredeem bonu point claim call identifi code expir',
 'urgent mobil award bonu caller prize final tri contact u call landlin box wr c ppm',
 'new address appl pair malarki',
 'today voda number end select receiv award match pleas call quot claim code standard rate app',
 'go sao mu today done',
 'predict wat time finish buy',
 'good stuff',
 'know yetund sent money yet sent text bother send dont involv anyth impos anyth first place apologis',
 'room',
 'hey girl r u hope u r well del r bak long time c give call sum time lucyxx',
 'k k much cost',
 'home',
 'dear call tmorrow pl accomod',
 'first answer question',
 'sunshin quiz wkli q win top soni dvd player u know countri algarv txt ansr sp tyron',
 'want get laid tonight want real dog locat sent direct ur mob join uk largest dog network bt txting gravel nt ec p msg p',
 'haf msn yiju hotmail com',
 'call meet',
 'check room befor activ',
 'rcv msg chat svc free hardcor servic text go u get noth u must age verifi yr network tri',
 'got c lazi type forgot lect saw pouch like v nice',
 'k text way',
 'sir wait mail',
 'swt thought nver get tire littl thing lovabl person coz somtim littl thing occupi biggest part heart gud ni',
 'know pl open back',
 'ye see ya dot',
 'what staff name take class us',
 'freemsg repli text randi sexi femal live local luv hear u netcollex ltd p per msg repli stop end',
 'ummma call check life begin qatar pl pray hard',
 'k delet contact',
 'sindu got job birla soft',
 'wine flow never',
 'yup thk cine better co need go plaza mah',
 'ok ur typic repli',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'everywher dirt floor window even shirt sometim open mouth come flow dream world without half chore time joy lot tv show see guess like thing must exist like rain hail mist time done becom one',
 'aaooooright work',
 'leav hous',
 'hello love get interview today happi good boy think miss',
 'custom servic annonc new year deliveri wait pleas call arrang deliveri',
 'winner u special select receiv cash holiday flight inc speak live oper claim',
 'keep safe need miss alreadi envi everyon see real life',
 'new car hous parent new job hand',
 'love excit day spend make happi',
 'pl stop bootydeli f invit friend repli ye see www sm ac u bootydeli stop send stop frnd',
 'bangbab ur order way u receiv servic msg download ur content u goto wap bangb tv ur mobil internet servic menu',
 'place ur point e cultur modul alreadi',
 'urgent tri contact last weekend draw show prize guarante call claim code valid hr',
 'hi frnd best way avoid missunderstd wit belov one',
 'great escap fanci bridg need lager see tomo',
 'ye complet form clark also utter wast',
 'sir need axi bank account bank address',
 'hmmm thk sure got time hop ard ya go free abt muz call u discuss liao',
 'time come later',
 'bloodi hell cant believ forgot surnam mr ill give u clue spanish begin',
 'well gonna finish bath good fine night',
 'let know got money carlo make call',
 'u still go mall',
 'turn friend stay whole show back til lt gt feel free go ahead smoke lt gt worth',
 'text doesnt repli let know log',
 'hi spoke maneesha v like know satisfi experi repli toll free ye',
 'lift hope offer money need especi end month approach hurt studi anyway gr weekend',
 'lol u trust',
 'ok gentleman treat digniti respect',
 'guy close',
 'go noth great bye',
 'hello handsom find job lazi work toward get back net mummi boytoy miss',
 'haha awesom minut',
 'pleas call custom servic repres freephon pm guarante cash prize',
 'got xma radio time get',
 'ju reach home go bath first si use net tell u finish k',
 'uniqu enough find th august www areyouuniqu co uk',
 'sorri join leagu peopl dont keep touch mean great deal friend time even great person cost great week',
 'hi final complet cours',
 'stop howev suggest stay someon abl give or everi stool',
 'hope settl new school year wishin gr day',
 'gud mrng dear hav nice day',
 'u got person stori',
 'hamster dead hey tmr meet pm orchard mrt',
 'hi kate even hope see tomorrow bit bloodi babyjontet txt back u xxx',
 'found enc lt gt',
 'sent lt gt buck',
 'hello darlin ive finish colleg txt u finish u love kate xxx',
 'account refil success inr lt decim gt keralacircl prepaid account balanc rs lt decim gt transact id kr lt gt',
 'goodmorn sleep ga',
 'u call alter ok',
 'say like dat dun buy ericsson oso cannot oredi lar',
 'enter cabin pa said happi b day boss felt special askd lunch lunch invit apart went',
 'aight yo dat straight dogg',
 'pleas give us connect today lt decim gt refund bill',
 'shoot big load get readi',
 'bruv hope great break reward semest',
 'home alway chat',
 'k k good studi well',
 'yup noe leh',
 'sound great home',
 'final match head toward draw predict',
 'tire slept well past night',
 'easi ah sen got select mean good',
 'take exam march',
 'yeah think use gt atm regist sure anyway help let know sure readi',
 'ok prob take ur time',
 'os call ubandu run without instal hard disk use os copi import file system give repair shop',
 'sorri call later',
 'u say leh cours noth happen lar say v romant ju bit lor thk e nite sceneri nice leh',
 'new mobil must go txt nokia collect today www tc biz optout gbp mtmsg',
 'would realli appreci call need someon talk',
 'u meet ur dream partner soon ur career flyng start find free txt horo follow ur star sign e g horo ari',
 'hey compani elama po mudyadhu',
 'life strict teacher bcoz teacher teach lesson amp conduct exam life first conduct exam amp teach lesson happi morn',
 'dear good morn',
 'get gandhipuram walk cross cut road right side lt gt street road turn first right',
 'dear go rubber place',
 'sorri batteri die yeah',
 'ye tv alway avail work place',
 'text meet someon sexi today u find date even flirt u join p repli name age eg sam msg recd thirtyeight penc',
 'print oh lt gt come upstair',
 'ill littl closer like bu stop street',
 'wil reach',
 'new theori argument win situat lose person dont argu ur friend kick amp say alway correct',
 'u secret admir look make contact u find r reveal think ur special call',
 'tomarrow final hear laptop case cant',
 'pleassssssseeeee tel v avent done sportsx',
 'okay shine meant sign sound better',
 'although told u dat baig face watch realli like e watch u gave co fr u thanx everyth dat u done today touch',
 'u rememb old commerci',
 'late said websit dont slipper',
 'ask call ok',
 'kalli wont bat nd inning',
 'didnt work oh ok goodnight fix readi time wake dearli miss good night sleep',
 'congratul ur award cd voucher gift guarante free entri wkli draw txt music tnc www ldew com win ppmx age',
 'ranjith cal drpd deeraj deepak min hold',
 'wen ur lovabl bcum angri wid u dnt take serious coz angri childish n true way show deep affect care n luv kettoda manda nice day da',
 '',
 'up day also ship compani take wk way usp take week get lag may bribe nipost get stuff',
 'back lemm know readi',
 'necessarili expect done get back though headin',
 'mmm yummi babe nice jolt suzi',
 'lover need',
 'tri contact repli offer video handset anytim network min unlimit text camcord repli call',
 'park next mini come today think',
 'yup',
 'anyway go shop co si done yet dun disturb u liao',
 'luton ring ur around h',
 'hey realli horni want chat see nake text hot text charg pm unsubscrib text stop',
 'dint come us',
 'wana plan trip sometm',
 'sure yet still tri get hold',
 'ur rington servic chang free credit go club mobil com choos content stop txt club stop p wk club po box mk wt',
 'evo download flash jealou',
 'rington club get uk singl chart mobil week choos top qualiti rington messag free charg',
 'come mu sort narcot situat',
 'night end anoth day morn come special way may smile like sunni ray leav worri blue blue bay',
 'hmv bonu special pound genuin hmv voucher answer easi question play send hmv info www percent real com',
 'usf guess might well take car',
 'object bf come',
 'thanx',
 'tell rob mack gf theater',
 'awesom see bit',
 'sent type food like',
 'done hand celebr full swing yet',
 'got call tool',
 'wen u miss someon person definit special u person special miss keep touch gdeve',
 'ok ask money far',
 'oki',
 'yeah think usual guy still pass last night get ahold anybodi let know throw',
 'k might come tonight class let earli',
 'ok',
 'hi babi im cruisin girl friend r u give call hour home that alright fone fone love jenni xxx',
 'life mean lot love life love peopl life world call friend call world ge',
 'dear shall mail tonit busi street shall updat tonit thing look ok varunnathu edukkukaye raksha ollu good one real sens',
 'hey told name gautham ah',
 'haf u found feel stupid da v cam work',
 'oop got bit',
 'much buzi',
 'accident delet messag resend pleas',
 'mobil custom may claim free camera phone upgrad pay go sim card loyalti call offer end thfeb c appli',
 'unless situat go gurl would appropri',
 'hurt teas make cri end life die plz keep one rose grave say stupid miss u nice day bslvyl',
 'cant pick phone right pl send messag',
 'need coffe run tomo believ time week alreadi',
 'awesom rememb last time got somebodi high first time diesel v',
 'shit realli shock scari cant imagin second def night u think somewher could crash night save taxi',
 'oh way food fridg want go meal tonight',
 'womdarful actor',
 'sm ac blind date u rodd aberdeen unit kingdom check http img sm ac w icmb cktz r blind date send hide',
 'yup remb think book',
 'jo ask u wana meet',
 'lol ye friendship hang thread caus u buy stuff',
 'themob check newest select content game tone gossip babe sport keep mobil fit funki text wap',
 'garag key bookshelf',
 'today accept day u accept brother sister lover dear best clo lvblefrnd jstfrnd cutefrnd lifpartnr belovd swtheart bstfrnd rpli mean enemi',
 'think ur smart win week weekli quiz text play cs winnersclub po box uz gbp week',
 'say give call friend got money definit buy end week',
 'hi way u day normal way real ur uniqu hope know u rest mylif hope u find wot lost',
 'made day great day',
 'k k advanc happi pongal',
 'hmmm guess go kb n power yoga haha dunno tahan power yoga anot thk got lo oso forgot liao',
 'realli dude friend afraid',
 'decemb mobil mth entitl updat latest colour camera mobil free call mobil updat co free',
 'coffe cake guess',
 'merri christma babe love ya kiss',
 'hey dont go watch x men lunch haha',
 'cud u tell ppl im gona b bit l co buse hav gon past co full im still waitin pete x',
 'would great guild could meet bristol road somewher get touch weekend plan take flight good week',
 'problem',
 'call messag miss call',
 'hi da today class',
 'say good sign well know track record read women',
 'cool text park',
 'read text sent meant joke read light',
 'k k apo k good movi',
 'mayb could get book tomo return immedi someth',
 'call germani penc per minut call fix line via access number prepay direct access',
 'chanc might evapor soon violat privaci steal phone number employ paperwork cool pleas contact report supervisor',
 'valentin day special win quiz take partner trip lifetim send go p msg rcvd custcar',
 'ta daaaaa home babe still',
 'cool come havent wine dine',
 'sleep surf',
 'sorri call later',
 'u call right call hand phone',
 'ok great thanx lot',
 'take post come must text happi read one wiv hello carolin end favourit bless',
 'u hide stranger',
 'interest like',
 'sister clear two round birla soft yesterday',
 'gudnit tc practic go',
 'di yiju ju saw ur mail case huim havent sent u num di num',
 'one small prestig problem',
 'fanci shag interest sextextuk com txt xxuk suzi txt cost per msg tnc websit x',
 'check realli miss see jeremiah great month',
 'nah help never iphon',
 'car hour half go apeshit',
 'today sorri day ever angri ever misbehav hurt plz plz slap urself bcoz ur fault basic good',
 'yo guy ever figur much need alcohol jay tri figur much safe spend weed',
 'lt gt ish minut minut ago wtf',
 'thank call forgot say happi onam sirji fine rememb met insur person meet qatar insha allah rakhesh ex tata aig join tissco tayseer',
 'congratul ur award cd voucher gift guarante free entri wkli draw txt music tnc www ldew com win ppmx age',
 'ur cash balanc current pound maxim ur cash send cash p msg cc hg suit land row w j hl',
 'actor work work even sleep late sinc unemploy moment alway sleep late unemploy everi day saturday',
 'hello got st andrew boy long way cold keep post',
 'ha ha cool cool chikku chikku db',
 'oh ok prob',
 'check audrey statu right',
 'busi tri finish new year look forward final meet',
 'good afternoon sunshin dawn day refresh happi aliv breath air smile think love alway',
 'well know z take care worri',
 'update_now xma offer latest motorola sonyericsson nokia free bluetooth doubl min txt orang call mobileupd call optout f q',
 'discount code rp stop messag repli stop www regalportfolio co uk custom servic',
 'wat uniform get',
 'cool text readi',
 'hello boytoy geeee miss alreadi woke wish bed cuddl love',
 'spoil bed well',
 'go bath msg next lt gt min',
 'cant keep talk peopl sure pay agre price pl tell want realli buy much will pay',
 'thank rington order refer charg gbp per week unsubscrib anytim call custom servic',
 'say happen',
 'could seen recognis face',
 'well lot thing happen lindsay new year sigh bar ptbo blue heron someth go',
 'keep payasam rinu bring',
 'taught ranjith sir call sm like becau he verifi project prabu told today pa dont mistak',

In [9]:
# Dependent Feature (Label - Output feature)
y=pd.get_dummies(messages["label"],dtype=int)
y

      ham  spam
0       1     0
1       1     0
2       0     1
3       1     0
4       1     0
...   ...   ...
5567    0     1
5568    1     0
5569    1     0
5570    1     0
5571    1     0

[5572 rows x 2 columns]

In [10]:
y=y.iloc[:,1].values

## Train Test Split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(corpus,y,test_size=0.20)

In [11]:
# Create BOW model
from sklearn.feature_extraction.text import CountVectorizer
## Binary BOW enable
cv=CountVectorizer(max_features=2500,ngram_range=(1,2))

In [12]:
# Independent Feature
X_train=cv.fit_transform(X_train).toarray()
X_test=cv.transform(X_test).toarray()

In [13]:
X_train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [14]:
cv.vocabulary_

{'pl': 1588,
 'confirm': 401,
 'time': 2140,
 'collect': 369,
 'tone': 2167,
 'within': 2417,
 'next': 1434,
 'hr': 991,
 'term': 2096,
 'condit': 399,
 'pleas': 1604,
 'see': 1839,
 'pg': 1569,
 'term condit': 2097,
 'forward': 718,
 'free': 722,
 'entri': 618,
 'weekli': 2378,
 'comp': 389,
 'send': 1851,
 'word': 2429,
 'enter': 614,
 'www': 2452,
 'com': 376,
 'free entri': 727,
 'entri weekli': 619,
 'hey': 931,
 'girl': 793,
 'hope': 968,
 'well': 2381,
 'del': 512,
 'bak': 137,
 'long': 1199,
 'give': 795,
 'call': 239,
 'sum': 2041,
 'long time': 1201,
 'give call': 796,
 'haha': 893,
 'sound': 1962,
 'crazi': 446,
 'dunno': 580,
 'dont': 555,
 'know': 1100,
 'second': 1834,
 'weak': 2364,
 'like': 1169,
 'keep': 1079,
 'eat': 590,
 'day': 488,
 'anyth': 79,
 'chang': 316,
 'sure': 2052,
 'noth': 1463,
 'ur': 2255,
 'paper': 1537,
 'morn': 1368,
 'aft': 30,
 'tmr': 2151,
 'ur paper': 2272,
 'sing': 1906,
 'think': 2119,
 'also': 58,
 'import': 1018,
 'find': 689,
 'someon': 1942,
 'place': 1596,
 'prefer': 1646,
 'smart': 1930,
 'help': 929,
 'even': 627,
 'thing': 2118,
 'choos': 334,
 'phone': 1570,
 'plan': 1597,
 'requir': 1760,
 'ask': 105,
 'especi': 621,
 'understand': 2243,
 'wine': 2409,
 'good': 828,
 'idea': 1007,
 'new': 1426,
 'hous': 984,
 'friend': 741,
 'alreadi': 55,
 'told': 2164,
 'done': 554,
 'okay': 1499,
 'name': 1405,
 'price': 1652,
 'wen': 2384,
 'pick': 1578,
 'ave': 120,
 'xx': 2464,
 'much': 1391,
 'case': 295,
 'cost': 428,
 'track': 2185,
 'quit': 1685,
 'get': 777,
 'minut': 1323,
 'sun': 2043,
 'ah': 37,
 'thk': 2124,
 'mayb': 1286,
 'dun': 576,
 'book': 190,
 'lesson': 1159,
 'pilat': 1583,
 'orchard': 1522,
 'mrt': 1383,
 'noe': 1446,
 'si': 1893,
 'catch': 303,
 'show': 1886,
 'afternoon': 32,
 'watch': 2353,
 'wan': 2329,
 'today': 2156,
 'lor': 1207,
 'wan watch': 2333,
 'enough': 613,
 'famili': 658,
 'hot': 980,
 'reason': 1719,
 'go': 803,
 'invit': 1039,
 'actual': 15,
 'wait': 2324,
 'seriou': 1863,
 'best': 162,
 'msg': 1385,
 'hard': 913,
 'person': 1565,
 'one': 1504,
 'make': 1254,
 'fall': 656,
 'love': 1216,
 'amp': 62,
 'back': 132,
 'ruin': 1795,
 'friendship': 746,
 'night': 1440,
 'fall love': 657,
 'love amp': 1217,
 'friendship good': 747,
 'good night': 837,
 'ok': 1489,
 'bu': 219,
 'come': 379,
 'soon': 1956,
 'otherwis': 1528,
 'tomorrow': 2166,
 'wish': 2411,
 'feel': 673,
 'alon': 53,
 'tyler': 2231,
 'could': 433,
 'could get': 434,
 'wors': 2436,
 'use': 2288,
 'half': 897,
 'way': 2356,
 'stop': 2010,
 'better': 163,
 'complet': 393,
 'tri': 2191,
 'figur': 682,
 'suppos': 2050,
 'coupl': 436,
 'differ': 529,
 'peopl': 1557,
 'week': 2370,
 'said': 1804,
 'togeth': 2163,
 'set': 1869,
 'date': 486,
 'tri figur': 2193,
 'sorri': 1957,
 'later': 1126,
 'sorri call': 1958,
 'call later': 251,
 'problem': 1665,
 'thanx': 2113,
 'hand': 900,
 'shop': 1883,
 'celebr': 309,
 'that': 2114,
 'earli': 584,
 'write': 2446,
 'put': 1678,
 'mode': 1355,
 'cover': 438,
 'press': 1649,
 'lt': 1231,
 'gt': 868,
 'gentli': 776,
 'remov': 1742,
 'interest': 1036,
 'go write': 817,
 'lt gt': 1233,
 'ur hand': 2261,
 'hi': 934,
 'darlin': 483,
 'hi darlin': 937,
 'dinner': 535,
 'go dinner': 807,
 'sunshin': 2046,
 'happi': 907,
 'breath': 209,
 'air': 43,
 'smile': 1931,
 'alway': 59,
 'good afternoon': 829,
 'bill': 167,
 'bad': 134,
 'sign': 1898,
 'number': 1471,
 'pin': 1584,
 'right': 1774,
 'babe': 129,
 'far': 664,
 'da': 474,
 'mo': 1338,
 'dead': 497,
 'sleep': 1921,
 'sofa': 1937,
 'cool': 423,
 'im': 1013,
 'great': 860,
 'connect': 407,
 'men': 1300,
 'co': 356,
 'never': 1425,
 'old': 1501,
 'lead': 1143,
 'look': 1203,
 'goe': 822,
 'monday': 1361,
 'suck': 2037,
 'lick': 1165,
 'everi': 630,
 'drop': 572,
 'readi': 1710,
 'bag': 136,
 'open': 1510,
 'room': 1785,
 'til': 2138,
 'without': 2419,
 'meet': 1291,
 'fren': 738,
 'muz': 1401,
 'guy': 888,
 'rite': 1780,
 'dun wan': 579,
 'wan meet': 2332,
 'exam': 640,
 'horribl': 977,
 'gal': 760,
 'sch': 1824,
 'stuff': 2029,
 'got': 843,
 'full': 752,
 'joke': 1068,
 'school': 1826,
 'seem': 1843,
 'holla': 962,
 'movi': 1377,
 'juz': 1074,
 'last': 1120,
 'decis': 507,
 'mah': 1248,
 'lar': 1117,
 'tot': 2178,
 'still': 2005,
 'mom': 1358,
 'check': 326,
 'yo': 2490,
 'nake': 1404,
 'deep': 509,
 'get readi': 782,
 'boytoy': 205,
 'food': 710,
 'around': 97,
 'buy': 228,
 'go buy': 806,
 'dear': 499,
 'subscrib': 2034,
 'draw': 564,
 'gift': 790,
 'voucher': 2320,
 'receipt': 1720,
 'correct': 427,
 'an': 66,
 'birthday': 169,
 'txt': 2212,
 'answer': 75,
 'draw gift': 565,
 'gift voucher': 792,
 'anybodi': 76,
 'thought': 2128,
 'alex': 49,
 'auction': 116,
 'round': 1788,
 'bid': 165,
 'luck': 1236,
 'good luck': 835,
 'lol': 1196,
 'princess': 1654,
 'yup': 2496,
 'fri': 739,
 'take': 2067,
 'leav': 1146,
 'one day': 1505,
 'abl': 2,
 'offic': 1484,
 'good morn': 836,
 'work': 2431,
 'end': 605,
 'anoth': 71,
 'special': 1972,
 'may': 1285,
 'sunni': 2045,
 'ray': 1701,
 'worri': 2435,
 'blue': 184,
 'gud': 882,
 'mrng': 1381,
 'anoth day': 72,
 'morn come': 1369,
 'gud mrng': 884,
 'type': 2232,
 'reach': 1705,
 'liao': 1163,
 'shirt': 1880,
 'mani': 1265,
 'car': 288,
 'urgent': 2279,
 'vri': 2322,
 'hv': 1001,
 'lac': 1107,
 'di': 524,
 'amt': 65,
 'prob': 1663,
 'gt lac': 873,
 'secret': 1835,
 'admir': 20,
 'reveal': 1769,
 'opt': 1516,
 'repli': 1749,
 'per': 1559,
 'care': 290,
 'secret admir': 1836,
 'reveal think': 1770,
 'special call': 1974,
 'shit': 1881,
 'face': 652,
 'game': 761,
 'almost': 52,
 'want': 2336,
 'want go': 2339,
 'serious': 1864,
 'spell': 1978,
 'let': 1160,
 'money': 1362,
 'carlo': 294,
 'let know': 1161,
 'got money': 849,
 'comin': 387,
 'fetch': 680,
 'us': 2287,
 'oredi': 1524,
 'nobodi': 1445,
 'wat': 2348,
 'miss': 1328,
 'sorri miss': 1960,
 'miss call': 1331,
 'pleas call': 1605,
 'call back': 241,
 'ill': 1012,
 'slow': 1924,
 'lol ok': 1197,
 'age': 35,
 'uk': 2235,
 'sex': 1872,
 'fun': 755,
 'text': 2099,
 'st': 1990,
 'player': 1602,
 'two': 2211,
 'life': 1166,
 'sometim': 1948,
 'forget': 715,
 'noon': 1457,
 'time make': 2145,
 'break': 208,
 'reward': 1772,
 'semest': 1849,
 'hope great': 972,
 'winner': 2410,
 'valu': 2297,
 'network': 1422,
 'custom': 465,
 'select': 1845,
 'prize': 1658,
 'claim': 339,
 'code': 359,
 'valid': 2295,
 'hour': 983,
 'claim call': 340,
 'call claim': 243,
 'claim code': 341,
 'landlin': 1113,
 'got call': 844,
 'call landlin': 250,
 'brother': 214,
 'transfer': 2188,
 'pa': 1532,
 'gt lt': 874,
 'plenti': 1609,
 'lucki': 1237,
 'awak': 123,
 'decid': 504,
 'low': 1227,
 'bore': 191,
 'near': 1414,
 'tv': 2209,
 'thank': 2111,
 'pic': 1577,
 'pretti': 1651,
 'vodafon': 2317,
 'digit': 531,
 'receiv': 1721,
 'award': 124,
 'match': 1273,
 'number end': 1473,
 'select receiv': 1846,
 'receiv award': 1722,
 'match pleas': 1274,
 'parent': 1538,
 'child': 330,
 'job': 1063,
 'support': 2049,
 'ride': 1773,
 'anyway': 83,
 'hurt': 1000,
 'join': 1066,
 'pray': 1644,
 'talk': 2071,
 'guess': 887,
 'somebodi': 1941,
 'fanci': 659,
 'wanna': 2335,
 'min': 1313,
 'give us': 797,
 'medic': 1290,
 'nigeria': 1439,
 'listen': 1180,
 'dirti': 539,
 'live': 1182,
 'chat': 323,
 'total': 2179,
 'mp': 1378,
 'india': 1025,
 'oh': 1486,
 'rang': 1695,
 'howev': 987,
 'fr': 720,
 'home': 963,
 'eve': 626,
 'bit': 173,
 'happen': 905,
 'pub': 1671,
 'sport': 1985,
 'mobil': 1343,
 'mistak': 1333,
 'charg': 319,
 'bt': 216,
 'free msg': 731,
 'mobil number': 1349,
 'call free': 246,
 'opinion': 1513,
 'abt': 3,
 'charact': 317,
 'wat ur': 2352,
 'batteri': 144,
 'mr': 1380,
 'uncl': 2242,
 'cold': 365,
 'sad': 1798,
 'cal': 238,
 'sir': 1908,
 'nokia': 1447,
 'motorola': 1374,
 'mth': 1387,
 'linerent': 1177,
 'net': 1420,
 'mobileupd': 1353,
 'optout': 1518,
 'nokia motorola': 1451,
 'min txt': 1318,
 'call mobileupd': 254,
 'mobileupd call': 1354,
 'call optout': 255,
 'someth': 1946,
 'sell': 1848,
 'fast': 665,
 'easi': 587,
 'want send': 2344,
 'em': 600,
 'box': 198,
 'file': 683,
 'tell': 2087,
 'call tell': 261,
 'everyth': 637,
 'bless': 179,
 'cancel': 280,
 'yeah': 2476,
 'babi': 131,
 'ring': 1776,
 'fone': 709,
 'kate': 1077,
 'win': 2402,
 'ipod': 1044,
 'excit': 643,
 'eye': 651,
 'visit': 2313,
 'ur mobil': 2271,
 'co uk': 358,
 'cuz': 471,
 'realli': 1715,
 'hair': 896,
 'rington': 1777,
 'gr': 854,
 'top': 2175,
 'wk': 2421,
 'get ur': 785,
 'everi week': 633,
 'send stop': 1855,
 'leh': 1152,
 'nite': 1444,
 'smoke': 1932,
 'spend': 1979,
 'tell friend': 2088,
 'smoke much': 1933,
 'xy': 2467,
 'neva': 1424,
 'sort': 1961,
 'bring': 211,
 'along': 54,
 'content': 416,
 'page': 1534,
 'cash': 296,
 'speak': 1969,
 'oper': 1511,
 'pm': 1614,
 'special select': 1976,
 'speak live': 1970,
 'live oper': 1184,
 'oper claim': 1512,
 'havent': 917,
 'dad': 476,
 'tonight': 2172,
 'meant': 1288,
 'mm': 1335,
 'nt': 1465,
 'gd': 772,
 'nice': 1437,
 'cant': 283,
 'man': 1259,
 'hope nice': 973,
 'cant wait': 286,
 'ye': 2473,
 'ye princess': 2474,
 'treat': 2190,
 'sub': 2033,
 'releas': 1737,
 'remind': 1741,
 'die': 527,
 'gram': 856,
 'come get': 381,
 'wonder': 2427,
 'huh': 996,
 'close': 352,
 'yup thk': 2498,
 'sat': 1813,
 'bugi': 224,
 'frm': 748,
 'den': 519,
 'hop': 967,
 'cine': 336,
 'hip': 942,
 'hip hop': 943,
 'sexi': 1873,
 'bun': 225,
 'ador': 22,
 'loverboy': 1226,
 'rememb': 1740,
 'sister': 1910,
 'law': 1137,
 'grin': 865,
 'sexi bun': 1874,
 'colleg': 372,
 'current': 462,
 'situat': 1913,
 'less': 1157,
 'expens': 646,
 'unless': 2244,
 'rate': 1696,
 'pleas go': 1606,
 'less expens': 1158,
 'account': 8,
 'credit': 449,
 'messag': 1303,
 'activ': 14,
 'cs': 455,
 'biz': 175,
 'free text': 734,
 'text messag': 2105,
 'txt word': 2224,
 'cs www': 458,
 'slowli': 1925,
 'becom': 152,
 'final': 687,
 'part': 1543,
 'follow': 708,
 'happi day': 909,
 'run': 1796,
 'ttyl': 2205,
 'fuck': 751,
 'nxt': 1476,
 'coz': 439,
 'dont make': 557,
 'town': 2184,
 'roommat': 1786,
 'took': 2174,
 'forev': 714,
 'ok come': 1490,
 'eng': 608,
 'rock': 1782,
 'sm': 1927,
 'futur': 757,
 'servic': 1866,
 'repli stop': 1754,
 'stop custom': 2012,
 'custom servic': 468,
 'realis': 1713,
 'busi': 227,
 'bother': 195,
 'outta': 1530,
 'gr day': 855,
 'troubl': 2197,
 'convinc': 421,
 'tel': 2086,
 'read': 1708,
 'pass': 1547,
 'need': 1416,
 'littl': 1181,
 'experi': 647,
 'voic': 2318,
 'still need': 2006,
 'email': 601,
 'gone': 826,
 'drive': 571,
 'test': 2098,
 'yet': 2486,
 'privat': 1656,
 'statement': 2001,
 'un': 2239,
 'redeem': 1726,
 'point': 1624,
 'identifi': 1008,
 'expir': 648,
 'privat account': 1657,
 'account statement': 9,
 'statement show': 2002,
 'show un': 1889,
 'un redeem': 2240,
 'redeem point': 1727,
 'point call': 1625,
 'call identifi': 248,
 'identifi code': 1009,
 'code expir': 360,
 'jada': 1053,
 'kusruthi': 1104,
 'lovabl': 1213,
 'silent': 1899,
 'spl': 1981,
 'matur': 1279,
 'stylish': 2032,
 'simpl': 1902,
 'opinion jada': 1514,
 'jada kusruthi': 1054,
 'kusruthi lovabl': 1105,
 'lovabl silent': 1215,
 'silent spl': 1900,
 'spl charact': 1982,
 'charact matur': 318,
 'matur stylish': 1280,
 'simpl pl': 1903,
 'pl repli': 1594,
 'xxx': 2465,
 'schedul': 1825,
 'saw': 1819,
 'ard': 92,
 'nd': 1411,
 'play': 1599,
 'say': 1820,
 'start': 1998,
 'march': 1269,
 'yesterday': 2485,
 'practic': 1643,
 'savamob': 1815,
 'member': 1298,
 'offer': 1480,
 'access': 7,
 'detail': 522,
 'pobox': 1619,
 'la': 1106,
 'wu': 2450,
 'savamob member': 1816,
 'member offer': 1299,
 'savamob pobox': 1817,
 'offer mobil': 1481,
 'orang': 1520,
 'line': 1174,
 'rental': 1745,
 'latest': 1129,
 'camera': 276,
 'updat': 2252,
 'stoptxt': 2019,
 'half price': 898,
 'line rental': 1176,
 'latest camera': 1130,
 'camera phone': 278,
 'phone free': 1573,
 'exactli': 639,
 'dont know': 556,
 'dude': 574,
 'longer': 1202,
 'probabl': 1664,
 'swing': 2064,
 'finish': 696,
 'yeah probabl': 2478,
 'effect': 594,
 'irrit': 1046,
 'ignor': 1010,
 'first': 697,
 'sight': 1897,
 'remain': 1739,
 'till': 2139,
 'maintain': 1253,
 'meet call': 1292,
 'shall': 1876,
 'mum': 1392,
 'danc': 480,
 'throw': 2130,
 'bare': 141,
 'stay': 2003,
 'fight': 681,
 'hav': 915,
 'mrng dear': 1382,
 'hav nice': 916,
 'nice day': 1438,
 'year': 2480,
 'went': 2386,
 'parti': 1545,
 'new year': 1432,
 'pay': 1552,
 'will': 2401,
 'world': 2434,
 'yep': 2481,
 'obvious': 1479,
 'real': 1711,
 'mean': 1287,
 'opportun': 1515,
 'studi': 2028,
 'go home': 809,
 'anyway go': 84,
 'go sch': 812,
 'bout': 197,
 'haf': 892,
 'found': 719,
 'stupid': 2030,
 'cam': 271,
 'alrit': 57,
 'delet': 514,
 'sim': 1901,
 'ur fone': 2259,
 'heard': 920,
 'freemsg': 736,
 'horni': 976,
 'ltd': 1234,
 'stop end': 2013,
 'record': 1724,
 'insid': 1031,
 'outsid': 1529,
 'bedroom': 155,
 'forgot': 716,
 'dont want': 559,
 'success': 2036,
 'morn dear': 1370,
 'wont': 2428,
 'disturb': 543,
 'sigh': 1896,
 'surpris': 2056,
 'cafe': 235,
 'mu': 1390,
 'like lt': 1172,
 'weed': 2369,
 'class': 347,
 'ya': 2468,
 'tho': 2126,
 'aight': 41,
 'still want': 2007,
 'want get': 2338,
 'workin': 2433,
 'eh': 597,
 'wit': 2416,
 'dem': 518,
 'save': 1818,
 'relat': 1735,
 'tuition': 2207,
 'mind': 1320,
 'go one': 811,
 'gonna': 827,
 'pop': 1632,
 'weekend': 2376,
 'free call': 725,
 'sir wait': 1909,
 'wait call': 2325,
 'angri': 67,
 'gave': 766,
 'month': 1363,
 'standard': 1995,
 'uz': 2292,
 'pobox uz': 1621,
 'yiju': 2488,
 'regard': 1732,
 'god': 819,
 'flower': 707,
 'touch': 2180,
 'gotta': 851,
 'walk': 2328,
 'across': 11,
 'sea': 1830,
 'goe day': 823,
 'across sea': 12,
 'trust': 2200,
 'armand': 96,
 'bath': 143,
 'dog': 550,
 'pete': 1568,
 'shd': 1878,
 'plu': 1610,
 'ok said': 1495,
 'hmv': 951,
 'bonu': 188,
 'pound': 1636,
 'question': 1683,
 'info': 1029,
 'percent': 1564,
 'play send': 1601,
 'moon': 1366,
 'children': 333,
 'song': 1950,
 'mob': 1340,
 'chariti': 322,
 'poli': 1627,
 'zed': 2499,
 'profit': 1667,
 'ur mob': 2270,
 'tell ur': 2089,
 'clean': 348,
 'heart': 921,
 'blood': 180,
 'ten': 2090,
 'miracl': 1326,
 'say slowli': 1823,
 'slowli god': 1926,
 'god love': 821,
 'amp need': 64,
 'need clean': 1417,
 'clean heart': 349,
 'heart blood': 922,
 'blood send': 181,
 'send ten': 1856,
 'ten special': 2091,
 'special peopl': 1975,
 'peopl amp': 1558,
 'amp miracl': 63,
 'miracl tomorrow': 1327,
 'pl pl': 1593,
 'art': 102,
 'whatev': 2391,
 'hook': 966,
 'omg': 1502,
 'cat': 302,
 'bad day': 135,
 'offici': 1485,
 'england': 610,
 'colour': 373,
 'flag': 702,
 'yer': 2482,
 'wx': 2459,
 'get offici': 781,
 'poli rington': 1628,
 'rington colour': 1778,
 'colour flag': 375,
 'flag yer': 703,
 'yer mobil': 2483,
 'text tone': 2107,
 'optout txt': 1519,
 'txt eng': 2216,
 'eng stop': 609,
 'stop box': 2011,
 'box wx': 203,
 'doubl': 561,
 'bluetooth': 185,
 'doubl min': 562,
 'met': 1306,
 'turn': 2208,
 'deal': 498,
 'costa': 431,
 'sol': 1938,
 'holiday': 958,
 'await': 121,
 'toclaim': 2154,
 'sae': 1800,
 'tc': 2076,
 'sk': 1914,
 'xh': 2461,
 'max': 1281,
 'well done': 2382,
 'costa del': 432,
 'del sol': 513,
 'sol holiday': 1939,
 'holiday await': 959,
 'await collect': 122,
 'collect call': 370,
 'call toclaim': 262,
 'toclaim sae': 2155,
 'sae tc': 1802,
 'tc pobox': 2077,
 'pobox stockport': 1620,
 'sk xh': 1915,
 'xh cost': 2462,
 'cost pm': 429,
 'pm max': 1616,
 'max min': 1282,
 'gym': 889,
 'kalli': 1075,
 'caller': 266,
 'attempt': 112,
 'asap': 103,
 'qp': 1680,
 'ppm': 1640,
 'urgent mobil': 2280,
 'bonu caller': 189,
 'caller prize': 268,
 'prize nd': 1662,
 'nd attempt': 1412,
 'attempt reach': 114,
 'reach call': 1706,
 'call asap': 240,
 'asap box': 104,
 'box qp': 201,
 'qp ppm': 1681,
 'way could': 2357,
 'campu': 279,
 'bed': 154,
 'spoke': 1983,
 'woke': 2425,
 'first time': 698,
 'fine': 694,
 'big': 166,
 'take care': 2068,
 'watch tv': 2354,
 'tv lor': 2210,
 'sent': 1860,
 'cum': 460,
 'mail': 1251,
 'id': 1006,
 'contact': 409,
 'ur mail': 2268,
 'mail id': 1252,
 'what': 2390,
 'beer': 157,
 'sen': 1850,
 'kind': 1094,
 'advic': 25,
 'text back': 2100,
 'convey': 418,
 'rakhesh': 1693,
 'qatar': 1679,
 'convey regard': 420,
 'everi night': 632,
 'solv': 1940,
 'laptop': 1116,
 ...}

In [15]:
# Algorithm
from sklearn.naive_bayes import MultinomialNB
spam_detect_model=MultinomialNB().fit(X_train,y_train)

In [16]:
spam_detect_model

MultinomialNB()

In [17]:
y_pred=spam_detect_model.predict(X_test)

In [18]:
# Performance Check
from sklearn.metrics import accuracy_score,classification_report

In [19]:
print(accuracy_score(y_test,y_pred))

0.9847533632286996

In [20]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       958
           1       0.97      0.92      0.94       157

    accuracy                           0.98      1115
   macro avg       0.98      0.96      0.97      1115
weighted avg       0.98      0.98      0.98      1115